# Generated by Django 6.1.1 on 2026-09-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='b_day',
            new_name='b_date',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='lname',
            new_name='l_name',
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
